create table if not exists public.match_analyses (
    id bigint generated by default as identity primary key,
    match_key text not null,
    version integer not null check (version > 0),
    division text not null,
    match_date date not null,
    kickoff_time time,
    home_team text not null,
    away_team text not null,
    analyzed_at timestamptz not null default now(),
    match_snapshot jsonb not null default '{}'::jsonb,
    report_snapshot jsonb not null default '{}'::jsonb,
    external_context jsonb not null default '{}'::jsonb,
    gemini_result jsonb,
    unique (match_key, version)
);

create index if not exists match_analyses_latest_idx
    on public.match_analyses (match_key, version desc);

alter table public.match_analyses enable row level security;

-- Uygulama yalnızca Streamlit Secrets içindeki service role anahtarıyla erişir.
-- Bu nedenle anon/authenticated kullanıcı politikası açılmaz.
